extends:
  - './.eslintrc.base.yml'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
overrides:
  - rules:
      "@typescript-eslint/no-explicit-any": "warn"
      "@typescript-eslint/no-empty-function": "warn"
    files:
    - "*.ts"
